#!/bin/sh -ex

if [ -z "${MIRAGE_APPLICATION}" ]
then
  >&2 echo "\$MIRAGE_APPLICATION has not been defined."
  exit 1
fi

if [ -d .git ]; then
  git pull
fi

opam update -u
opam depext -i mirage ssl
eval `opam config env`
git clone git://github.com/mirage/mirage-${MIRAGE_APPLICATION}
cd mirage-${MIRAGE_APPLICATION}
export MODE=unix
make configure
make build
export MODE=xen
make configure
make build
echo MIRAGE WORKS
