#!/bin/sh -ex

#opam remote add mirage git://github.com/mirage/mirage-dev
opam update -u
opam installext lwt ssl cohttp
cohttpver=`opam list -i cohttp | grep -v '#' | awk '{print $2}'`
deps=`opam list --depends-on cohttp.${cohttpver} --rec -s`
eval `opam config env`
opam install $deps
echo MIRAGE WORKS
